### ISSUE TITLE
MSX cassette commands do not work.

### ISSUE THREAD

**Issue by cdoty** [wavemotion-dave/ColecoDS#2]
It appears to be using a standard layout instead of the MSX layout. The quotes in the command generate the @ symbol.

**Comment by wavemotion-dave** [comment]
Strange. I just tested it and with both the Japanese BIOS/Keyboard and EU BIOS/Keyboard the quotes seem to generate quotes. And I'm able to run all cassette games. 

Do you know the CRC of the MSX bios you are using?

Edit: Just tried it with the stock msx.rom BIOS as well as all of the alternatives I support - in each case, it seems to render the keyboard properly and generates the double-quote both from the virtual keyboard and also from the Cassette Menu to load games. 

If you are using just msx.rom as your BIOS, be sure it matches the CRC I have in my readme.md file... or at least make sure it's an EU BIOS.  The readme should give you alternate bios files you can use for Japanese and EU machines.

**Comment by cdoty** [comment]
It's the HB-10 bios and the CRC is 0f488dd8.
I also see it on the PV-7 bios, and that has a CRC of ee229390.
I switched to another system BIOS and it worked fine.

**Comment by wavemotion-dave** [comment]
Okay... yeah, the BIOS setup isn't ideal right now. In addition to msx.rom which is any generic EU bios, you also can have the following installed (preferably exactly named as shown though variations are allowed):

* e9ccd789  cx5m.rom    - Yamaha's UK/EU Machine with 32K of RAM
* 5486b711  hx-10.rom   - Toshiba's UK/EU Machine with 64K of RAM
* ee229390  hb-10.rom   - Sony HitBit JP Machine with 16K of RAM (uses the Japanese matrix)
* 5ad03407  fs-1300.rom - National JP Machine with 64K of RAM (uses the Japanese matrix)
* ee229390  pv-7.rom    - Casio PV-7 with just 8K of RAM! If you can't find this BIOS, use pv-16.rom or hb-10.rom

And then in Global Configuration you can pick the default machine you would like to use or you can change it on a per-game basis.

The MSX1 bioses don't provide for a lot of variation - so finding one that works is probably all you care about. I do like to be able to sometimes use a Japanese BIOS with the alternate keyboard layout because it looks cool :)

I'm going to close this issue down. Thanks for the feedback - it's always hugely appreciated!
